spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8081
ru:
  otus:
    homework:
      library:
        base-url: http://localhost:8080