server:
  port: 0

licenseUrl: classpath:license.xml

security: 
  enabled: false
  oauth2: 
    client: 
      clientId:
      clientSecret: 
      scope:
      accessTokenUri:
      userAuthorizationUri:
    resource: 
      jwt: 
        key-uri:

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:     
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:/liquibase/rootChangeLog.xml
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    stream:
      binders:
        binderName:
          type: kafka
      bindings:
        eventHelloPublish:
          destination: event-hello
        eventHelloSubscribe:
          destination: event-hello